"""Initial core structure

Revision ID: 1474bb6e743b
Revises: 
Create Date: 2026-01-16 17:47:29.664753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1474bb6e743b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('diameter', sa.String(length=10), nullable=True),
    sa.Column('season', sa.String(length=20), nullable=True),
    sa.Column('is_spaiked', sa.Boolean(), nullable=True),
    sa.Column('full_name', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_manual_edited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_products_brand'), 'master_products', ['brand'], unique=False)
    op.create_index(op.f('ix_master_products_is_manual_edited'), 'master_products', ['is_manual_edited'], unique=False)
    op.create_index(op.f('ix_master_products_model'), 'master_products', ['model'], unique=False)
    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('original_url', sa.String(length=500), nullable=False),
    sa.Column('s3_key', sa.String(length=500), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['master_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_images_file_hash'), 'product_images', ['file_hash'], unique=False)
    op.create_index(op.f('ix_product_images_master_id'), 'product_images', ['master_id'], unique=False)
    op.create_index(op.f('ix_product_images_source'), 'product_images', ['source'], unique=False)
    op.create_table('raw_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('vendor', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['master_id'], ['master_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_products_external_id'), 'raw_products', ['external_id'], unique=False)
    op.create_index(op.f('ix_raw_products_master_id'), 'raw_products', ['master_id'], unique=False)
    op.create_index(op.f('ix_raw_products_source'), 'raw_products', ['source'], unique=False)
    op.create_index(op.f('ix_raw_products_vendor'), 'raw_products', ['vendor'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_products_vendor'), table_name='raw_products')
    op.drop_index(op.f('ix_raw_products_source'), table_name='raw_products')
    op.drop_index(op.f('ix_raw_products_master_id'), table_name='raw_products')
    op.drop_index(op.f('ix_raw_products_external_id'), table_name='raw_products')
    op.drop_table('raw_products')
    op.drop_index(op.f('ix_product_images_source'), table_name='product_images')
    op.drop_index(op.f('ix_product_images_master_id'), table_name='product_images')
    op.drop_index(op.f('ix_product_images_file_hash'), table_name='product_images')
    op.drop_table('product_images')
    op.drop_index(op.f('ix_master_products_model'), table_name='master_products')
    op.drop_index(op.f('ix_master_products_is_manual_edited'), table_name='master_products')
    op.drop_index(op.f('ix_master_products_brand'), table_name='master_products')
    op.drop_table('master_products')
    # ### end Alembic commands ###
