"""Add unique constraint to RawProducr

Revision ID: ebb5b53600c8
Revises: 1474bb6e743b
Create Date: 2026-01-17 16:32:41.317384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebb5b53600c8'
down_revision: Union[str, Sequence[str], None] = '1474bb6e743b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_source_external_id_uc', 'raw_products', ['source', 'external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_source_external_id_uc', 'raw_products', type_='unique')
    # ### end Alembic commands ###
